[project]
name = "velograph"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "elasticsearch>=9.2.1",
    "fastapi>=0.128.0",
    "uvicorn>=0.40.0",
]
readme = "README.md"
